name: Linux CMake
on:
  workflow_call:
    inputs:
      preparation_commands:
        description: "Commands to run to prepare the build"
        required: false
        type: string
        default: ''
      extra_resolve_options:
        description: "Extra Resolve Options"
        type: string
        required: false
env:
  EXTRA_RESOLVE_OPTIONS: ${{ github.event.inputs.extra_resolve_options }}
jobs:
  docker_builds:
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        config:
          - container: ghcr.io/steinwurf/cmake-3.12-gcc:1.0.0
            name: Cmake 3.12.4 (GCC)
          - container: ghcr.io/steinwurf/cmake-3.12-clang:1.0.0
            name: Cmake 3.12.4 (Clang)
    runs-on: [self-hosted, docker, builder]
    name: ${{ matrix.config.name }}
    container:
      image: ${{ matrix.config.container }}
      options: --user 0:0
      volumes:
        - /home/buildbot/.ssh:/root/.ssh
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Preparation Commands
        if: inputs.preparation_commands != ''
        run: ${{ inputs.preparation_commands }}
      - name: CMake Cleanup
        run: cmake -E remove_directory build
      - name: CMake Setup
        run: cmake -E make_directory build
      - name: CMake Configure
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 15
          command: cd build && cmake ../ -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DSTEINWURF_RESOLVE_OPTIONS="--git_protocol=git@ $EXTRA_RESOLVE_OPTIONS"
      - name: CMake Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build .
